//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystem.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class cours
    {
        public cours()
        {
            this.contents = new HashSet<content>();
            this.enrolls = new HashSet<enroll>();
            this.notices = new HashSet<notice>();
        }
    
        public int courseid { get; set; }
        public string coursename { get; set; }
        public string cdescription { get; set; }
        public string cteacher { get; set; }
        public System.TimeSpan cstart { get; set; }
        public System.TimeSpan cend { get; set; }
        public string cpic { get; set; }
        public int cprice { get; set; }
        public string session { get; set; }
    
        public virtual ICollection<content> contents { get; set; }
        public virtual ICollection<enroll> enrolls { get; set; }
        public virtual ICollection<notice> notices { get; set; }
    }
}
