//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystem.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class document
    {
        public int docid { get; set; }
        public int uid { get; set; }
        public string docname { get; set; }
        public string docpath { get; set; }
    
        public virtual user user { get; set; }
    }
}
