//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystem.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class library
    {
        public library()
        {
            this.bookborrows = new HashSet<bookborrow>();
        }
    
        public int lid { get; set; }
        public string bookname { get; set; }
        public int quantity { get; set; }
        public int available { get; set; }
        public string bookpic { get; set; }
        public string writtername { get; set; }
        public string writterdesc { get; set; }
    
        public virtual ICollection<bookborrow> bookborrows { get; set; }
    }
}
