//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystem.Models.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniversityManagementContext1 : DbContext
    {
        public UniversityManagementContext1()
            : base("name=UniversityManagementContext1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admins { get; set; }
        public DbSet<bookborrow> bookborrows { get; set; }
        public DbSet<content> contents { get; set; }
        public DbSet<cours> courses { get; set; }
        public DbSet<document> documents { get; set; }
        public DbSet<employee> employees { get; set; }
        public DbSet<enroll> enrolls { get; set; }
        public DbSet<library> libraries { get; set; }
        public DbSet<notice> notices { get; set; }
        public DbSet<payment> payments { get; set; }
        public DbSet<photoorder> photoorders { get; set; }
        public DbSet<skill> skills { get; set; }
        public DbSet<student> students { get; set; }
        public DbSet<teacher> teachers { get; set; }
        public DbSet<user> users { get; set; }
    }
}
