//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystem.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public student()
        {
            this.payments = new HashSet<payment>();
        }
    
        public int studnetid { get; set; }
        public int uid { get; set; }
        public string cgpa { get; set; }
        public string department { get; set; }
        public System.DateTime dob { get; set; }
        public System.DateTime addmissiondate { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<payment> payments { get; set; }
        public virtual user user { get; set; }
    }
}
