//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystem.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.admins = new HashSet<admin>();
            this.documents = new HashSet<document>();
            this.employees = new HashSet<employee>();
            this.students = new HashSet<student>();
            this.teachers = new HashSet<teacher>();
        }
    
        public int uid { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int type { get; set; }
        public string dp { get; set; }
    
        public virtual ICollection<admin> admins { get; set; }
        public virtual ICollection<document> documents { get; set; }
        public virtual ICollection<employee> employees { get; set; }
        public virtual ICollection<student> students { get; set; }
        public virtual ICollection<teacher> teachers { get; set; }
    }
}
